services:
    online_market_web:
        container_name: online_market_web
        image: nginx:alpine
        ports:
            - "8040:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - online_market_app
        networks:
            - online_market_network

    online_market_app:
        container_name: online_market_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - online_market_db
        volumes:
            - ./:/var/www
        networks:
            - online_market_network
        ports:
            - "9090:9000"

    online_market_db:
        image: mysql
        container_name: online_market_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - online_market_database:/var/lib/mysql
        networks:
            - online_market_network
        expose:
            - 3344
networks:
    online_market_network:
        driver: bridge
volumes:
    online_market_database:
